changelog:
  categories:
    - title: Features
      labels:
        - enhancement
        - feat
    - title: Fixes
      labels:
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Chore
      labels:
        - chore
        - dependencies
  exclude:
    labels:
      - ignore-for-release
